### PR TITLE
submodules updater and test builds

### PR DESCRIPTION
**Pull request by seiya-git**
For test builds and checking submodule updates for master branch
(should be merged after SMP folder update #11)

### CODE REVIEW

**Comment by realfinder** [comment]
don't know if this use GCC or Windows Visual Studio, but I think it's better to make it use GCC so it can be build for Linux and cross-compiled for windows from Linux and use source from last official libass commits and other libraries

**Comment by seiya-git** [comment]
@realfinder, GCC is used for linux and Visual Studio MSBuild for Windows
I can't build mingw64 version for windows, it's says error avisynth is missing, but lib in correct directory
https://github.com/pinterf/assrender/blob/master/src/CMakeLists.txt#L39

**Comment by seiya-git** [comment]
@realfinder, Added Windows GCC github build script, now it's should work
also small fix to Windows MINGW build script

**Comment by realfinder** [comment]
> @realfinder, Added Windows GCC github build script, but it's not working

how it not working? anyway let see @qyot27 said

**Comment by realfinder** [comment]
still not get it to work? C API cross-compiles should be fine https://github.com/AviSynth/AviSynthPlus/issues/281

**Comment by seiya-git** [comment]
@realfinder yes, mingw build not work and I don't know how to fix it, anyway we have Visual Studio build

**Comment by pinterf** [comment]
Since #11 is merged, should this one be merged as well or we can expect further changes?

**Comment by seiya-git** [comment]
@pinterf can we split README.md to BUILD.md, CHANGELOG.md and README.md with links in README.md to BUILD.md and CHANGELOG.md?

**Comment by pinterf** [comment]
Definitely yes.

**Comment by seiya-git** [comment]
@pinterf done! Everything works now, you can merge it.
I commented mingw64 build in GitHub CI since it's not working outside the msys2 for now

**Pull request merged**
